#!/bin/sh
# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: 0BSD
#MISE description="Verify repository licensing metadata"
#MISE tools={"pipx:reuse"="6.2.0","aqua:EmbarkStudios/cargo-deny"="0.19.0"}

set -eu

reuse lint

if [ -f Cargo.toml ]; then
    cargo-deny check
fi
